// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: acuri.proto

package v0

import (
	v0 "github.com/scurid/acuri-api/pkg/grpc/entity/v0"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetElementListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Customer *v0.Customer `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"` // customer identity issued by Scurid; this is a unique DID issued per customer's organization
}

func (x *GetElementListReq) Reset() {
	*x = GetElementListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acuri_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetElementListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetElementListReq) ProtoMessage() {}

func (x *GetElementListReq) ProtoReflect() protoreflect.Message {
	mi := &file_acuri_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetElementListReq.ProtoReflect.Descriptor instead.
func (*GetElementListReq) Descriptor() ([]byte, []int) {
	return file_acuri_proto_rawDescGZIP(), []int{0}
}

func (x *GetElementListReq) GetCustomer() *v0.Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type GetElementListRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Element []*v0.Element `protobuf:"bytes,1,rep,name=element,proto3" json:"element,omitempty"` // array of elements per customer
}

func (x *GetElementListRes) Reset() {
	*x = GetElementListRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_acuri_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetElementListRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetElementListRes) ProtoMessage() {}

func (x *GetElementListRes) ProtoReflect() protoreflect.Message {
	mi := &file_acuri_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetElementListRes.ProtoReflect.Descriptor instead.
func (*GetElementListRes) Descriptor() ([]byte, []int) {
	return file_acuri_proto_rawDescGZIP(), []int{1}
}

func (x *GetElementListRes) GetElement() []*v0.Element {
	if x != nil {
		return x.Element
	}
	return nil
}

var File_acuri_proto protoreflect.FileDescriptor

var file_acuri_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x61, 0x63, 0x75, 0x72, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61,
	0x63, 0x75, 0x72, 0x69, 0x2e, 0x76, 0x30, 0x1a, 0x0c, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x44, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x2f, 0x0a, 0x08, 0x63, 0x75,
	0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x52, 0x08, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x22, 0x41, 0x0a, 0x11, 0x47,
	0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x12, 0x2c, 0x0a, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x76, 0x30, 0x2e, 0x45, 0x6c,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x65, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0x59,
	0x0a, 0x09, 0x41, 0x63, 0x75, 0x72, 0x69, 0x53, 0x61, 0x61, 0x53, 0x12, 0x4c, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x2e,
	0x61, 0x63, 0x75, 0x72, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d,
	0x65, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x61, 0x63, 0x75,
	0x72, 0x69, 0x2e, 0x76, 0x30, 0x2e, 0x47, 0x65, 0x74, 0x45, 0x6c, 0x65, 0x6d, 0x65, 0x6e, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x63, 0x75, 0x72, 0x69, 0x64, 0x2f, 0x61,
	0x63, 0x75, 0x72, 0x69, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70,
	0x63, 0x2f, 0x61, 0x63, 0x75, 0x72, 0x69, 0x2f, 0x76, 0x30, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_acuri_proto_rawDescOnce sync.Once
	file_acuri_proto_rawDescData = file_acuri_proto_rawDesc
)

func file_acuri_proto_rawDescGZIP() []byte {
	file_acuri_proto_rawDescOnce.Do(func() {
		file_acuri_proto_rawDescData = protoimpl.X.CompressGZIP(file_acuri_proto_rawDescData)
	})
	return file_acuri_proto_rawDescData
}

var file_acuri_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acuri_proto_goTypes = []interface{}{
	(*GetElementListReq)(nil), // 0: acuri.v0.GetElementListReq
	(*GetElementListRes)(nil), // 1: acuri.v0.GetElementListRes
	(*v0.Customer)(nil),       // 2: entity.v0.Customer
	(*v0.Element)(nil),        // 3: entity.v0.Element
}
var file_acuri_proto_depIdxs = []int32{
	2, // 0: acuri.v0.GetElementListReq.customer:type_name -> entity.v0.Customer
	3, // 1: acuri.v0.GetElementListRes.element:type_name -> entity.v0.Element
	0, // 2: acuri.v0.AcuriSaaS.GetElementList:input_type -> acuri.v0.GetElementListReq
	1, // 3: acuri.v0.AcuriSaaS.GetElementList:output_type -> acuri.v0.GetElementListRes
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_acuri_proto_init() }
func file_acuri_proto_init() {
	if File_acuri_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_acuri_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetElementListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_acuri_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetElementListRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_acuri_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_acuri_proto_goTypes,
		DependencyIndexes: file_acuri_proto_depIdxs,
		MessageInfos:      file_acuri_proto_msgTypes,
	}.Build()
	File_acuri_proto = out.File
	file_acuri_proto_rawDesc = nil
	file_acuri_proto_goTypes = nil
	file_acuri_proto_depIdxs = nil
}
